# Latex document creation make file
# Created: 01/27/2011

# location of the the tex setup (i.e. make file libs, sty files etc) library directory
TEXLIBDIR=	../../../tex

# per make file vars
TEX=		GroupProject
FINAL_PDF_NAME=	../$(TEX).pdf

#all:		$(TEX).dvi
all:		showpdf

#include $(TEXLIBDIR)/lib/make-slides.mk
include $(TEXLIBDIR)/lib/make-bib.mk
include $(TEXLIBDIR)/lib/make-cmd.mk
